package jp.ac.aiit.pbl.disaster.hypocenter;

import java.util.Arrays;

/**
 * This enum have definitions of SeismicEpicenter.
 * They are ID and Regions name of SeismicEpicenter with Japanese.
 * this enum class provides methods to get a property and get a RegionName associated with the id.
 */

public enum SeismicEpicenter {
    
    HokkaidoRegion(11, "北海道地方"),
    TohokuRegion(12, "東北地方"),
    HokurikuRegion(13, "北陸地方"),
    KantoKoshinRegion(14, "関東甲信地方"),
    OgasawaraRegion(15, "小笠原地方"),
    TokaiRegion(16, "東海地方"),
    KinkiRegion(17, "近畿地方"),
    ChugokuRegion(18, "中国地方"),
    ShikokuRegion(19, "四国地方"),
    KyushuRegion(20, "九州地方"),
    OkinawaRegion(21, "沖縄地方"),
    IshikariNorth(100, "石狩地方北部"),
    IshikariCentral(101, "石狩地方中部"),
    IshikariSouth(102, "石狩地方南部"),
    OshimaNorth(105, "渡島地方北部"),
    OshimaEast(106, "渡島地方東部"),
    OshimaWest(107, "渡島地方西部"),
    HiyamaRegion(110, "檜山地方"),
    ShiribeshiNorth(115, "後志地方北部"),
    ShiribeshiEast(116, "後志地方東部"),
    ShiribeshiWest(117, "後志地方西部"),
    SorachiNorth(120, "空知地方北部"),
    SorachiCentral(121, "空知地方中部"),
    SorachiSouth(122, "空知地方南部"),
    KamikawaNorth(125, "上川地方北部"),
    KamikawaCentral(126, "上川地方中部"),
    KamikawaSouth(127, "上川地方南部"),
    RumoiMiddleNorth(130, "留萌地方中北部"),
    RumoiSouth(131, "留萌地方南部"),
    SoyaNorth(135, "宗谷地方北部"),
    SoyaSouth(136, "宗谷地方南部"),
    AbashiriRegion(140, "網走地方"),
    KitamiRegion(141, "北見地方"),
    MonbetsuRegion(142, "紋別地方"),
    IburiWest(145, "胆振地方西部"),
    IburiMiddleEast(146, "胆振地方中東部"),
    HidakaWest(150, "日高地方西部"),
    HidakaCentral(151, "日高地方中部"),
    HidakaSouth(152, "日高地方東部"),
    TokachiNorth(155, "十勝地方北部"),
    TokachiCentral(156, "十勝地方中部"),
    TokachiSouth(157, "十勝地方南部"),
    KushiroNorth(160, "釧路地方北部"),
    KushiroMiddleSouth(161, "釧路地方中南部"),
    NemuroNorth(165, "根室地方北部"),
    NemuroCentral(166, "根室地方中部"),
    NemuroSouth(167, "根室地方南部"),
    HokkaidoOffshoreSouthWest(180, "北海道南西沖"),
    HokkaidoOffshoreWest(181, "北海道西方沖"),
    IshikariBay(182, "石狩湾"),
    HokkaidoOffshoreNorthWest(183, "北海道北西沖"),
    SoyaStrait(184, "宗谷海峡"),
    NearKunashiriIsland(186, "国後島付近"),
    NearEtorofuIsland(187, "択捉島付近"),
    HokkaidoOffshoreEast(188, "北海道東方沖"),
    NemuroPeninsulaOffshoreSouthEast(189, "根室半島南東沖"),
    KushiroOffshore(190, "釧路沖"),
    TokachiOffshore(191, "十勝沖"),
    UrakawaOffshore(192, "浦河沖"),
    TomakomaiOffshore(193, "苫小牧沖"),
    UchiuraBay(194, "内浦湾"),
    SoyaOffshoreEast(195, "宗谷東方沖"),
    AbashiriOffshore(196, "網走沖"),
    EtrofuOffshoreSouthEast(197, "択捉島南東沖"),
    AomoriPrefectureTsugaruNorth(200, "青森県津軽北部"),
    AomoriPrefectureTsugaruSouth(201, "青森県津軽南部"),
    AomoriPrefectureSanpachiKamikita(202, "青森県三八上北地方"),
    AomoriPrefectureShimokita(203, "青森県下北地方"),
    IwatePrefectureNorthernCoast(210, "岩手県沿岸北部"),
    IwatePrefectureSouthernCoast(211, "岩手県沿岸南部"),
    IwatePrefectureNorthInland(211, "岩手県内陸北部"),
    IwatePrefectureSouthInland(212, "岩手県内陸南部"),
    MiyagiPrefectureNorth(220, "宮城県北部"),
    MiyagiPrefectureSouth(221, "宮城県南部"),
    MiyagiPrefectureCentral(222, "宮城県中部"),
    AkitaPrefectureNorthernCoast(230, "秋田県沿岸北部"),
    AkitaPrefectureSouthernCoast(231, "秋田県沿岸南部"),
    AkitaPrefectureNorthInland(232, "秋田県内陸北部"),
    AkitaPrefectureSouthInland(233, "秋田県内陸南部"),
    YamagataPrefectureShonaiRegion(240, "山形県庄内地方"),
    YamagataPrefectureMogami(241, "山形県最上地方"),
    YamagataPrefectureMurayama(242, "山形県村山地方"),
    YamagataPrefectureOkitama(243, "山形県置賜地方"),
    FukushimaPrefectureNakadori(250, "福島県中通り"),
    FukushimaPrefectureHamadori(251, "福島県浜通り"),
    FukushimaPrefectureAizu(252, "福島県会津"),
    TsugaruStrait(280, "津軽海峡"),
    YamagataPrefectureOffshore(281, "山形県沖"),
    AkitaPrefectureOffshore(282, "秋田県沖"),
    AomoriPrefectureOffshoreWest(283, "青森県西方沖"),
    MutsuBay(284, "陸奥湾"),
    AomoriPrefectureOffshoreEast(285, "青森県西方沖"),
    IwatePrefectureOffshore(286, "岩手県沖"),
    MiyagiPrefectureOffshore(287, "宮城県沖"),
    SanrikuOffshore(288, "三陸沖"),
    FukushimaPrefectureOffshore(289, "福島県沖"),
    IbarakiPrefectureNorth(300, "茨城県北部"),
    IbarakiPrefectureSouth(301, "茨城県南部"),
    ChibaPrefectureOffshoreSouthEast(309, "千葉県南東沖"),
    TochigiPrefectureNorth(310, "栃木県北部"),
    TochigiPrefectureSouth(311, "栃木県南部"),
    GunmaPrefectureNorth(320, "群馬県北部"),
    GunmagiPrefectureSouth(321, "群馬県南部"),
    SaitamaPrefectureNorth(330, "埼玉県北部"),
    SaitamaPrefectureSouth(331, "埼玉県南部"),
    SaitamaPrefectureChichibu(332, "埼玉県秩父地方"),
    ChibaPrefectureNorthEast(330, "千葉県北東部"),
    ChibaPrefectureNorthWest(331, "千葉県北西部"),
    ChibaPrefectureSouth(342, "千葉県南部"),
    BosoPeninsulaOffshoreSouth(349, "房総半島南方沖"),
    Tokyo23Wards(350, "東京都23区"),
    TokyoTamaEast(351, "東京都多摩東部"),
    TokyoTamaWest(352, "東京都多摩西部"),
    KanagawaPrefectureEast(360, "神奈川県東部"),
    KanagawaPrefectureWest(361, "神奈川県西部"),
    NiigataPrefectureJoetsu(370, "新潟県上越地方"),
    NiigataPrefectureChuetsu(371, "新潟県上越地方"),
    NiigataPrefectureShimoetsu(372, "新潟県下越地方"),
    NiigataPrefectureOffshoreShimoetsu(378, "新潟県下越沖"),
    NiigataPrefectureOffshoreJochuetsu(379, "新潟県上中越沖"),
    ToyamaPrefectureEast(380, "富山県東部"),
    ToyamaPrefectureWest(381, "富山県西部"),
    IshikawaPrefectureNoto(390, "石川県能登地方"),
    IshikawaPrefectureKaga(391, "石川県加賀地方"),
    FukuiPrefectureReihoku(400, "福井県嶺北"),
    FukuiPrefectureReinan(401, "福井県嶺南"),
    YamanashiPrefectureCentralAndWest(411, "山梨県中・西部"),
    YamanashiPrefectureEastAndFujiFiveLakes(412, "山梨県東部・富士五湖"),
    NaganoPrefectureEast(420, "長野県東部"),
    NaganoPrefectureCentral(421, "長野県中部"),
    NaganoPrefectureWest(422, "長野県西部"),
    GifuPrefectureHida(430, "岐阜県飛騨地方"),
    GifuPrefectureMinoEast(431, "岐阜県美濃東部"),
    GifuPrefectureMinoCentralWest(432, "岐阜県美濃中西部"),
    ShizuokaPrefectureIzu(440, "静岡県伊豆地方"),
    ShizuokaPrefectureEast(441, "静岡県東部"),
    ShizuokaPrefectureCentral(442, "静岡県中部"),
    ShizuokaPrefectureWest(443, "静岡県西部"),
    AichiPrefectureEast(450, "愛知県東部"),
    AichiPrefectureWest(451, "愛知県西部"),
    MiePrefectureNorth(460, "三重県北部"),
    MiePrefectureCentral(461, "三重県中部"),
    MiePrefectureSouth(462, "三重県南部"),
    MiePrefectureOffshoreSouthEast(469, "三重県南東沖"),
    IbarakiPrefectureOffshore(471, "茨城県沖"),
    KantoOffshoreEast(472, "関東東方沖"),
    ChibaPrefectureOffshoreEast(473, "千葉県東方沖"),
    HachijojimaOffshoreEast(475, "八丈島東方沖"),
    NearSeaHachijojima(476, "八丈島近海"),
    TokyoBay(477, "東京湾"),
    SagamiBay(478, "相模湾"),
    NearSeaIzuOshima(480, "伊豆大島近海"),
    IzuOshimaOffshoreEast(481, "伊豆半島東方沖"),
    NearSeaMiyakejima(482, "三宅島近海"),
    NearSeaNiijimaAndKozushima(483, "新島・神津島近海"),
    SurugaBay(485, "駿河湾"),
    SurugaBayOffshoreSouth(486, "駿河湾南方沖"),
    EnshuNada(487, "遠州灘"),
    MikawaBay(489, "三河湾"),
    IseBay(490, "伊勢湾"),
    WakasaBay(492, "若狭湾"),
    FukuiPrefecturefshoreshore(	493,"福井県沖"),
    IshikawaPrefecturefshoreWest(494	,"石川県西方沖"),
    NotoPeninsulafshore(495,"能登半島沖"),
    ToyamaBay(497,"富山湾"),
    NearSado(498,"佐渡付近"),
    CoastTokaidofshoreSouth(499,"東海道南方沖"),
    ShigaPrefectureNorth(500,"滋賀県北部"),
    ShigaPrefectureSouth(501,"滋賀県南部"),
    KyotoNorth(510,"京都府北部"),
    KyotoSouth(511,"京都府南部"),
    OsakaPrefectureNorth(520,"大阪府北部"),
    OsakaPrefectureSouth(521,"大阪府南部"),
    HyogoPrefectureNorth(530,"兵庫県北部"),
    HyogoPrefectureSouast(531,"兵庫県南東部"),
    HyogoPrefectureSouthWest(532,"兵庫県南西部"),
    NaraPrefecture(540,"奈良県"),
    WakayamaPrefectureNorth(550,"和歌山県北部"),
    WakayamaPrefectureSouth(551,"和歌山県南部"),
    TottoriEast(560,"鳥取県東部"),
    TottoriPrefectureCentral(562,"鳥取県中部"),
    TottoriPrefectureWest(563,"鳥取県西部"),
    ShimaneEast(570,"島根県東部"),
    ShimaneWest(571,"島根県西部"),
    OkayamaPrefectureNorth(580,"岡山県北部"),
    OkayamaPrefectureSouth(581,"岡山県南部"),
    HiroshimaPrefectureNorth(590,"広島県北部"),
    EastHiroshimaSouth(591,"広島県南東部"),
    HiroshimaPrefectureSouthWest(592,"広島県南西部"),
    TokushimaPrefectureNorth(600,"徳島県北部"),
    TokushimaPrefectureSouth(601,"徳島県南部"),
    KagawaEast(610,"香川県東部"),
    KagawaWest(611,"香川県西部"),
    EhimePrefectureToyo(620,"愛媛県東予"),
    EhimePrefectureChuyo(621,"愛媛県中予"),
    EhimePrefectureNanyo(622,"愛媛県南予"),
    KochiEast(630,"高知県東部"),
    KochiPrefectureCentral(631,"高知県中部"),
    KochiPrefectureWest(632,"高知県西部"),
    TosaBay(673,"土佐湾"),
    KiiChannel(674,"紀伊水道"),
    OsakaBay(675,"大阪湾"),
    HarimaNada(676,"播磨灘"),
    SetoInlandSeaCentral(677,"瀬戸内海中部"),
    Akinada(678,"安芸灘"),
    SuoNada(679,"周防灘"),
    IyoNada(680,"伊予灘"),
    BungoChannel(681,"豊後水道"),
    YamaguchiPrefecturefshoreNorthWest(682,"山口県北西沖"),
    ShimanePrefecturefshore(683,"島根県沖"),
    TottoriPrefecturefshore(684,"鳥取県沖"),
    NearOkiIsland(685,"隠岐島近海"),
    HyogoPrefecturefshoreNorth(686,"兵庫県北方沖"),
    KyotoPrefecturefshore(687,"京都府沖"),
    NearAwajiIsland(688,"淡路島付近"),
    WakayamaPrefecturefshoreSouth(689,"和歌山県南方沖"),
    YamaguchiPrefectureNorth(700,"山口県北部"),
    YamaguchiPrefectureWest(702,"山口県西部"),
    YamaguchiPrefectureEast(703,"山口県東部"),
    YamaguchiPrefectureCentral(704,"山口県中部"),
    FukuokaPrefectureFukuoka(710,"福岡県福岡地方"),
    FukuokaPrefectureKitakyushu(711,"福岡県北九州地方"),
    FukuokaPrefectureChikuho(712,"福岡県筑豊地方"),
    FukuokaPrefectureChikugo(713,"福岡県筑後地方"),
    SagaPrefectureNorth(720,"佐賀県北部"),
    SagaPrefectureSouth(721,"佐賀県南部"),
    NorthNagasaki(730,"長崎県北部"),
    NagasakiPrefectureSouthWest(731,"長崎県南西部"),
    NagasakiPrefectureShimabaraPeninsula(732,"長崎県島原半島"),
    KumamotoAso(740,"熊本県阿蘇地方"),
    KumamotoPrefectureKumamoto(741,"熊本県熊本地方"),
    KumamotoPrefectureKuma(742,"熊本県球磨地方"),
    KumamotoPrefectureAmakusaAndAshikita(743,"熊本県天草・芦北地方"),
    OitaPrefectureNorth(750,"大分県北部"),
    OitaPrefectureCentral(751,"大分県中部"),
    OitaPrefectureSouth(752,"大分県南部"),
    OitaPrefectureWest(753,"大分県西部"),
    MiyazakiPrefectureNorthPlains(760,"宮崎県北部平野部"),
    MiyazakiPrefectureAlongNorthMountains(761,"宮崎県北部山沿い"),
    MiyazakiPrefectureSouthPlains(762,"宮崎県南部平野部"),
    MiyazakiPrefectureAlongSouthMountains(763,"宮崎県南部山沿い"),
    KagoshimaPrefectureSatsuma(770,"鹿児島県薩摩地方"),
    KagoshimaPrefectureOsumi(771,"鹿児島県大隅地方"),
    NearGotoIslands(783,"五島列島近海"),
    AmakusaNada(784,"天草灘"),
    AriakeSea(785,"有明海"),
    TachibanaBay(786,"橘湾"),
    KagoshimaBay(787,"鹿児島湾"),
    NearTanegashima(790,"種子島近海"),
    HinataNada(791,"日向灘"),
    NearAmamiOshima(793,"奄美大島近海"),
    NearIkiAndTsushima(795,"壱岐・対馬近海"),
    FukuokaPrefecturefshoreNorthWest(796,"福岡県北西沖"),
    SatsumaPeninsulafshoreWest(797,"薩摩半島西方沖"),
    NearTokaraArchipelago(798,"トカラ列島近海"),
    AmamiOshimafshoreNorthWest(799,"奄美大島北西沖"),
    OsumiPeninsulafshoreEast(820,"大隅半島東方沖"),
    KyushuOfffshoreSouthEast(821,"九州地方南東沖"),
    TanegashimaOffshoreSouthEast(822,"種子島南東沖"),
    AmamiOshimaOffshoreNorthEast(823,"奄美大島北東沖"),
    NearOkinawaMainIsland(850,"沖縄本島近海"),
    NearMinamidaitoIsland(851,"南大東島近海"),
    OkinawaMainIslandOffshoreSouth(852,"沖縄本島南方沖"),
    NearMiyakojima(853,"宮古島近海"),
    NearIshigakiIsland(854,"石垣島近海"),
    IshigakiIslandOffshoreSouth(855,"石垣島南方沖"),
    AroundIriomoteIsland(856,"西表島付近"),
    NearYonaguniIsland(857,"与那国島近海"),
    OkinawaMainIslandOffshoreNorthWest(858,"沖縄本島北西沖"),
    MiyakojimaOffshoreNorthWest(859,"宮古島北西沖"),
    IshigakiIslandOffshoreNorthWest(860,"石垣島北西沖"),
    NearTaiwan(900,"台湾付近"),
    EastChinaSea(901,"東シナ海"),
    ShikokuOffshore(902,"四国沖"),
    SeanearTorishima(903,"鳥島近海"),
    TorishimaIslandOffshore(904,"鳥島東方沖"),
    OkhotskSeaSouth(905,"オホーツク海南部"),
    SakhalinWest(906,"サハリン西方沖"),
    JapanSeaNorth(907,"日本海北部"),
    JapanSeaCentral(908,"日本海中部"),
    JapanSeaWest(909,"日本海西部"),
    NearChichijima(911,"父島近海"),
    KurilIslands(912,"千島列島"),
    KurilIslandsOffshoreSouthEast(913,"千島列島南東沖"),
    HokkaidoOffshoreSouthEast(914,"北海道南東沖"),
    TohokuRegionEast(915,"東北地方東方沖"),
    OgasawaraIslandsOffshoreWest(916,"小笠原諸島西方沖"),
    NearIwoJima(917,"硫黄島近海"),
    OgasawaraIslandsOffshoreEast(918,"小笠原諸島東方沖"),
    NankaidoOffshoreSouth(919,"南海道南方沖"),
    SatsunanIslandsEast(920,"薩南諸島東方沖"),
    HonshuOffshoreSouth(921,"本州南方沖"),
    NearSouthSakhalin(922,"サハリン南部付近"),
    NorthWestPacific(930,"北西太平洋"),
    MarianaIslands(932,"マリアナ諸島"),
    YellowSea(933,"黄海"),
    SouthKoreanPeninsula(934,"朝鮮半島南部"),
    NorthKoreanPeninsula(935,"朝鮮半島北部"),
    ChinaNorthEast(936,"中国東北部"),
    NearVladivostok(937,"ウラジオストク付近"),
    SiberiaSouth(938,"シベリア南部"),
    NearSakhalin(939,"サハリン近海"),
    AleutianIslands(940,"アリューシャン列島"),
    NearKamchatkaPeninsula(941,"カムチャツカ半島付近"),
    NorthAmericaWest(942,"北米西部"),
    NorthAmericaCentral(943,"北米中部"),
    NorthAmericaEast(944,"北米東部"),
    CentralAmerica(945,"中米"),
    SouthAmericaWest(946,"南米西部"),
    SouthAmericaCentral(947,"南米中部"),
    SouthAmericaEast(948,"南米東部"),
    NorthEastPacific(949,"北東太平洋"),
    SouthPacific(950,"南太平洋"),
    NearIndochinaPeninsula(951,"インドシナ半島付近"),
    NearPhilippines(952,"フィリピン付近"),
    NearIndonesia(953,"インドネシア付近"),
    NearGuam(954,"グアム付近"),
    NearNewGuinea(955,"ニューギニア付近"),
    NearNewZealand(956,"ニュージーランド付近"),
    NearAustralia(957,"オーストラリア付近"),
    NearSiberia(958,"シベリア付近"),
    RussiaWest(959,"ロシア西部"),
    RussiaCentral(960,"ロシア中部"),
    RussiaEast(961,"ロシア東部"),
    CentralAsia(962,"中央アジア"),
    ChinaWest(963,"中国西部"),
    ChinaCentral(964,"中国中部"),
    ChinaEast(965,"中国東部"),
    NearIndia(966,"インド付近"),
    IndianOcean(967,"インド洋"),
    MiddleEast(968,"中東"),
    EuropeWest(969,"ヨーロッパ西部"),
    EuropeCentral(970,"ヨーロッパ中部"),
    EuropeEast(971,"ヨーロッパ東部"),
    Mediterraneansea(972,"地中海"),
    AfricaWest(973,"アフリカ西部"),
    AfricaCentral(974,"アフリカ中部"),
    AfricaEast(975,"アフリカ東部"),
    NorthAtlantic(976,"北大西洋"),
    SouthAtlantic(977,"南大西洋"),
    NearNorthPole(978,"北極付近"),
    NearAntarctica(979,"南極付近"),
    Remoteplace(999,"遠地"),
    OtherEpicenterNames(1000,"その他の震央地名");
    //Epicentername(codenumber:NNN)(NNN,"震央地名(コード番号：NNN)"),
    
    private int code;
    private String regionName;
    
    private SeismicEpicenter(int code, String regionName){
        this.code = code;
        this.regionName = regionName;
    }
    
    public Integer getCode(){
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    
    public String getRegionName() {
        return regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }
    
    public static SeismicEpicenter getRegionName(int code){
        return Arrays.stream(SeismicEpicenter.values())
                .filter(data -> data.getCode().equals(code))
                .findFirst()
                .orElse(null);
    }
    
}
